name: Build

on:
  push:
    branches:
      - main
  pull_request:

env:
  REDO_HISTORY_PATH: ~/.bash_history
  REDO_EDITOR: vim

jobs:
  plugin_test:
    name: asdf plugin test
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: asdf_plugin_test
        uses: asdf-vm/actions/plugin-test@v1
        with:
          command: redo help
